name: sparse-neighbors-search
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - cython
  - numpy>=1.17
  - scikit-learn>=0.21
  - gxx_linux-64 #[no osx]
  - clangxx_osx-64 #[no linux]
  - openmp